// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejkjcqtqblfdqmqmxaca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqa2pjcXRxYmxmZHFtcW14YWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDkzOTQsImV4cCI6MjA1OTYyNTM5NH0.RVTMzWt14_c0GO2hyi2CR4Pl51cNo7uhmfqzUqo23Oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);